import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export async function setupProject(config) {
    const targetDir = path.join(process.cwd(), config.projectName);
    const templateDir = path.resolve(__dirname, '../templates/base');

    console.log(chalk.cyan(`\n🚀 Initializing MAI Agents in ${targetDir}...`));

    try {
        // 1. Create Directory
        await fs.ensureDir(targetDir);

        // 2. Copy Template Files
        // In a real scenario, we copy from templates/base. 
        // Here we assume templates/base is populated.
        if (fs.existsSync(templateDir)) {
            await fs.copy(templateDir, targetDir);
        } else {
            // Fallback for this environment where we might be actively moving things
            // or if templates/base isn't fully ready yet.
            console.log(chalk.yellow("Warning: Template directory not found. Creating basic structure."));
            await fs.ensureDir(path.join(targetDir, '.agents'));
            await fs.ensureDir(path.join(targetDir, 'workflows'));
            await fs.ensureDir(path.join(targetDir, 'config'));
        }

        // 3. Customize MAI_MEMORY.md based on config
        const memoryPath = path.join(targetDir, 'MAI_MEMORY.md');
        let memoryContent = `# 🧠 MAI MEMORY - ACTIVE CONTEXT

> Generated for project: ${config.projectName}
> **Created:** ${new Date().toISOString()}

---

## 📍 Active Context

**Current Phase:** Initialization
**Current Task:** Setup Complete
**Mode:** Active
**Default Language:** ${config.language.split(' ')[0]}
**Scale:** ${config.scale.split(' ')[0]}

---

## 👥 Agent Roster
(Standard MAI Agents loaded...)
`;

        await fs.writeFile(memoryPath, memoryContent);

        // 4. Create README
        const readmePath = path.join(targetDir, 'README.md');
        const readmeContent = `# 🤖 MAI Agents Project: ${config.projectName}

Autogenerated by MAI CLI.
Scale: ${config.scale}
Language: ${config.language}

Run \`mai help\` to see available commands.
`;
        await fs.writeFile(readmePath, readmeContent);

        console.log(chalk.green.bold('\n✅ Success! Project ready.'));
        console.log(chalk.white(`\n1. cd ${config.projectName}`));
        console.log(chalk.white('2. mai help'));
        console.log(chalk.white('3. /brainstorm "My First Idea"'));

    } catch (error) {
        console.error(chalk.red('Error during setup:'), error);
    }
}
