import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export async function setupProject(config) {
    let targetDir;

    if (config.deploymentTarget === 'Integrate into Current Project (Here)') {
        targetDir = process.cwd();
        // If integrating, current folder name is the project name
        config.projectName = path.basename(targetDir);
    } else {
        targetDir = path.join(process.cwd(), config.projectName);
    }

    console.log(chalk.cyan(`\n🚀 Initializing MAI Agents in ${targetDir}...`));

    try {
        // 1. Create Directory (only if new)
        await fs.ensureDir(targetDir);

        // 2. Copy Template Files SAFELY
        const templateDir = path.resolve(__dirname, '../templates/base');

        if (fs.existsSync(templateDir)) {
            // Copy the entire .agent directory (agents, workflows, skills)
            const agentSrc = path.join(templateDir, '.agent');
            const agentDest = path.join(targetDir, '.agent');
            if (fs.existsSync(agentSrc)) {
                await fs.copy(agentSrc, agentDest, { overwrite: true });
            }

            // Also copy config if it exists
            const configSrc = path.join(templateDir, 'config');
            const configDest = path.join(targetDir, 'config');
            if (fs.existsSync(configSrc)) {
                await fs.copy(configSrc, configDest, { overwrite: true });
            }
        } else {
            console.log(chalk.yellow("Warning: Template directory not found. Creating basic structure."));
            await fs.ensureDir(path.join(targetDir, '.agent', 'agents'));
            await fs.ensureDir(path.join(targetDir, '.agent', 'workflows'));
            await fs.ensureDir(path.join(targetDir, '.agent', 'skills'));
            await fs.ensureDir(path.join(targetDir, 'config'));
        }

        // 2.5 Copy Documentation (New Feature)
        const docsSrc = path.resolve(__dirname, '../docs');
        const docsDest = path.join(targetDir, 'docs');
        if (fs.existsSync(docsSrc)) {
            await fs.copy(docsSrc, docsDest, { overwrite: true });
        }

        // 3. Customize MAI_MEMORY.md (Always safe to overwrite or create?)
        // Better to check existence
        const memoryPath = path.join(targetDir, 'MAI_MEMORY.md');
        if (!fs.existsSync(memoryPath)) {
            let memoryContent = `# 🧠 MAI MEMORY - ACTIVE CONTEXT

> Generated for project: ${config.projectName}
> **Created:** ${new Date().toISOString()}

---

## 📍 Active Context

**Current Phase:** Initialization
**Current Task:** Setup Complete
**Mode:** Active
**Default Language:** ${config.language.split(' ')[0]}
**Scale:** ${config.scale.split(' ')[0]}

---

## 👥 Agent Roster
(Standard MAI Agents loaded...)
`;
            await fs.writeFile(memoryPath, memoryContent);
        } else {
            console.log(chalk.yellow('ℹ️ MAI_MEMORY.md already exists. Skipping creation.'));
        }

        // 4. Handle README safely
        const readmePath = path.join(targetDir, 'README.md');
        const maiReadmePath = path.join(targetDir, 'MAI_README.md');

        const readmeContent = `# 🤖 MAI Agents Project: ${config.projectName}

Autogenerated by MAI CLI.
Scale: ${config.scale}
Language: ${config.language}

Run \`mai help\` to see available commands.
`;

        if (fs.existsSync(readmePath)) {
            console.log(chalk.yellow('⚠️ README.md exists. Creating MAI_README.md instead.'));
            await fs.writeFile(maiReadmePath, readmeContent);
        } else {
            await fs.writeFile(readmePath, readmeContent);
        }

        console.log(chalk.green.bold('\n✅ Success! Project ready.'));
        if (config.deploymentTarget !== 'Integrate into Current Project (Here)') {
            console.log(chalk.white(`\n1. cd ${config.projectName}`));
        }
        console.log(chalk.white('2. mai help'));
        console.log(chalk.white('3. mai brainstorm "My First Idea"'));

    } catch (error) {
        console.error(chalk.red('Error during setup:'), error);
    }
}
